import React, { useState, useEffect } from 'react';
import { Activity, Search, Filter, Download, Calendar, User, AlertTriangle, Info, CheckCircle } from 'lucide-react';
import { api } from '../../utils/api';
import { Admin, SystemLog } from '../../types';

interface SystemLogsProps {
 user: Admin;
 onBack: () => void;
}

export const SystemLogs: React.FC<SystemLogsProps> = ({ user, onBack }) => {
 const [logs, setLogs] = useState<SystemLog[]>([]);
 const [loading, setLoading] = useState(true);
 const [searchTerm, setSearchTerm] = useState('');
 const [filterRole, setFilterRole] = useState('');
 const [filterAction, setFilterAction] = useState('');
 const [dateRange, setDateRange] = useState({ start: '', end: '' });
 const [page, setPage] = useState(1);
 const PAGE_SIZE = 50;

 useEffect(() => {
 loadLogs();
 }, []);

 const loadLogs = async () => {
 try {
 const logsData = await api.admin.getSystemLogs(user.role);
 setLogs(logsData as SystemLog[]);
 } catch (error) {
 console.error('Error loading system logs:', error);
 } finally {
 setLoading(false);
 }
 };

 const handleDownloadLogs = () => {
 const content = `
SYSTEM LOGS REPORT
==================
Generated: ${new Date().toLocaleDateString()}
Period: ${dateRange.start || 'All time'} to ${dateRange.end || 'Present'}
Total Logs: ${filteredLogs.length}

LOGS:
-----
${filteredLogs.map(log => `
${new Date(log.timestamp).toISOString()} | ${log.userRole.toUpperCase()} | ${log.userId} | ${log.action}
Details: ${log.details}
`).join('')}

Generated by: ${user.name}
System: Healthcare Management System
 `;
 
 const blob = new Blob([content], { type: 'text/plain' });
 const url = URL.createObjectURL(blob);
 const a = document.createElement('a');
 a.href = url;
 a.download = `system-logs-${new Date().toISOString().split('T')[0]}.txt`;
 document.body.appendChild(a);
 a.click();
 document.body.removeChild(a);
 URL.revokeObjectURL(url);
 };

 // Reset to page 1 when any filter changes
 React.useEffect(() => { setPage(1); }, [searchTerm, filterRole, filterAction, dateRange]);

 const filteredLogs = logs.filter(log => {
 const matchesSearch = log.action.toLowerCase().includes(searchTerm.toLowerCase()) ||
 log.details.toLowerCase().includes(searchTerm.toLowerCase()) ||
 log.userId.toLowerCase().includes(searchTerm.toLowerCase());
 
 const matchesRole = !filterRole || log.userRole === filterRole;
 const matchesAction = !filterAction || log.action.toLowerCase().includes(filterAction.toLowerCase());
 
 const logDate = new Date(log.timestamp);
 const matchesDateRange = (!dateRange.start || logDate >= new Date(dateRange.start)) &&
 (!dateRange.end || logDate <= new Date(dateRange.end));
 
 return matchesSearch && matchesRole && matchesAction && matchesDateRange;
 });

 const getActionIcon = (action: string) => {
 if (action.includes('LOGIN') || action.includes('LOGOUT')) {
 return <User className="w-4 h-4" />;
 } else if (action.includes('ERROR') || action.includes('FAILED')) {
 return <AlertTriangle className="w-4 h-4" />;
 } else if (action.includes('CREATED') || action.includes('COMPLETED')) {
 return <CheckCircle className="w-4 h-4" />;
 } else {
 return <Info className="w-4 h-4" />;
 }
 };

 const getActionColor = (action: string) => {
 if (action.includes('LOGIN') || action.includes('LOGOUT')) {
 return 'bg-blue-100 text-blue-600';
 } else if (action.includes('ERROR') || action.includes('FAILED')) {
 return 'bg-red-100 text-red-600';
 } else if (action.includes('CREATED') || action.includes('COMPLETED')) {
 return 'bg-green-100 text-green-600';
 } else {
 return 'bg-gray-100 text-gray-600';
 }
 };

 const getRoleColor = (role: string) => {
 const colors = {
 patient: 'bg-blue-100 text-blue-300',
 doctor: 'bg-green-100 text-emerald-300',
 hospital: 'bg-purple-100 text-violet-300',
 insurance: 'bg-orange-100 text-orange-300',
 bank: 'bg-teal-100 text-teal-800',
 admin: 'bg-red-100 text-red-300',
 };
 return colors[role as keyof typeof colors] || ' text-gray-800';
 };

 const uniqueRoles = [...new Set(logs.map(log => log.userRole))];
 const uniqueActions = [...new Set(logs.map(log => log.action))];

 if (loading) {
 return (
 <div className="flex items-center justify-center h-64">
 <div className="text-gray-500">Loading system logs...</div>
 </div>
 );
 }

 return (
 <div className="p-6 space-y-6 bg-gray-50 min-h-full">
 <div className="flex items-center justify-between">
 <div>
 <h1 className="text-2xl font-bold text-gray-900">System Logs</h1>
 <p className="text-gray-500">Monitor system activity and audit trail</p>
 </div>
 <div className="flex space-x-2">
 <button
 onClick={onBack}
 className="text-red-600 hover:text-red-600 font-medium"
 >
 Back to Dashboard
 </button>
 <button
 onClick={handleDownloadLogs}
 className="bg-red-600 text-gray-900 px-4 py-2 rounded-lg hover:bg-red-700 flex items-center space-x-2"
 >
 <Download className="w-4 h-4" />
 <span>Export Logs</span>
 </button>
 </div>
 </div>

 {/* Summary Stats */}
 <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
 <div className="bg-white p-6 rounded-xl border border-gray-200 ">
 <div className="flex items-center justify-between">
 <div>
 <p className="text-sm font-medium text-gray-500">Total Logs</p>
 <p className="text-3xl font-bold text-gray-900">{logs.length}</p>
 </div>
 <Activity className="w-8 h-8 text-red-600" />
 </div>
 </div>

 <div className="bg-white p-6 rounded-xl border border-gray-200 ">
 <div className="flex items-center justify-between">
 <div>
 <p className="text-sm font-medium text-gray-500">Today's Activity</p>
 <p className="text-3xl font-bold text-blue-600">
 {logs.filter(log => 
 new Date(log.timestamp).toDateString() === new Date().toDateString()
 ).length}
 </p>
 </div>
 <Calendar className="w-8 h-8 text-blue-600" />
 </div>
 </div>

 <div className="bg-white p-6 rounded-xl border border-gray-200 ">
 <div className="flex items-center justify-between">
 <div>
 <p className="text-sm font-medium text-gray-500">Active Users</p>
 <p className="text-3xl font-bold text-green-600">
 {new Set(logs.filter(log => 
 new Date(log.timestamp) > new Date(Date.now() - 24 * 60 * 60 * 1000)
 ).map(log => log.userId)).size}
 </p>
 </div>
 <User className="w-8 h-8 text-green-600" />
 </div>
 </div>

 <div className="bg-white p-6 rounded-xl border border-gray-200 ">
 <div className="flex items-center justify-between">
 <div>
 <p className="text-sm font-medium text-gray-500">Error Rate</p>
 <p className="text-3xl font-bold text-red-600">
 {logs.length > 0 ? 
 Math.round((logs.filter(log => log.action.includes('ERROR')).length / logs.length) * 100) : 0
 }%
 </p>
 </div>
 <AlertTriangle className="w-8 h-8 text-red-600" />
 </div>
 </div>
 </div>

 {/* Filters */}
 <div className="bg-white p-6 rounded-xl border border-gray-200 ">
 <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
 <div className="relative">
 <Search className="absolute left-3 top-3 w-4 h-4 text-gray-500" />
 <input
 type="text"
 placeholder="Search logs..."
 value={searchTerm}
 onChange={(e) => setSearchTerm(e.target.value)}
 className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
 />
 </div>
 
 <div className="relative">
 <Filter className="absolute left-3 top-3 w-4 h-4 text-gray-500" />
 <select
 value={filterRole}
 onChange={(e) => setFilterRole(e.target.value)}
 className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
 >
 <option value="">All Roles</option>
 {uniqueRoles.map(role => (
 <option key={role} value={role} className="capitalize">{role}</option>
 ))}
 </select>
 </div>
 
 <div>
 <select
 value={filterAction}
 onChange={(e) => setFilterAction(e.target.value)}
 className="bg-gray-100 w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
 >
 <option value="">All Actions</option>
 {uniqueActions.slice(0, 10).map(action => (
 <option key={action} value={action}>{action}</option>
 ))}
 </select>
 </div>
 
 <div>
 <input
 type="date"
 placeholder="Start Date"
 value={dateRange.start}
 onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
 className="bg-gray-100 w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
 />
 </div>
 
 <div>
 <input
 type="date"
 placeholder="End Date"
 value={dateRange.end}
 onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
 className="bg-gray-100 w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
 />
 </div>
 </div>
 </div>

 {/* Logs Table */}
 <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
 <div className="p-6 border-b border-gray-200">
 <h2 className="text-lg font-semibold text-gray-900">
 System Activity Logs ({filteredLogs.length})
 </h2>
 </div>
 <div className="overflow-x-auto">
 <table className="w-full">
 <thead className="bg-gray-50">
 <tr>
 <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
 Timestamp
 </th>
 <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
 User
 </th>
 <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
 Action
 </th>
 <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
 Details
 </th>
 </tr>
 </thead>
 <tbody className="bg-white divide-y divide-gray-200">
 {filteredLogs.slice((page-1)*PAGE_SIZE, page*PAGE_SIZE).map((log) => (
 <tr key={log.id} className="hover:bg-gray-50">
 <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
 <div className="space-y-1">
 <div>{new Date(log.timestamp).toLocaleDateString()}</div>
 <div className="text-gray-500">
 {new Date(log.timestamp).toLocaleTimeString()}
 </div>
 </div>
 </td>
 <td className="px-6 py-4 whitespace-nowrap">
 <div className="flex items-center space-x-2">
 <span className={`px-2 py-1 rounded-full text-xs font-medium ${getRoleColor(log.userRole)}`}>
 {log.userRole}
 </span>
 <span className="text-sm text-gray-900">{log.userId}</span>
 </div>
 </td>
 <td className="px-6 py-4 whitespace-nowrap">
 <div className="flex items-center space-x-2">
 <div className={`p-1 rounded-full ${getActionColor(log.action)}`}>
 {getActionIcon(log.action)}
 </div>
 <span className="text-sm font-medium text-gray-900">{log.action}</span>
 </div>
 </td>
 <td className="px-6 py-4">
 <div className="text-sm text-gray-900 max-w-md truncate">
 {log.details}
 </div>
 </td>
 </tr>
 ))}
 </tbody>
 </table>
 {filteredLogs.length === 0 && (
 <div className="text-center py-8 text-gray-500">
 No logs found matching your criteria
 </div>
 )}
 {filteredLogs.length > PAGE_SIZE && (
 <div className="flex items-center justify-between px-6 py-3 border-t border-gray-200 bg-gray-50">
 <span className="text-xs text-gray-500">
 Showing {Math.min((page-1)*PAGE_SIZE+1, filteredLogs.length)}–{Math.min(page*PAGE_SIZE, filteredLogs.length)} of {filteredLogs.length} logs
 </span>
 <div className="flex gap-2">
 <button onClick={() => setPage(p => Math.max(1, p-1))} disabled={page === 1}
 className="px-3 py-1 text-xs border border-gray-200 rounded-lg disabled:opacity-40 hover:bg-gray-100">← Prev</button>
 <span className="px-3 py-1 text-xs text-gray-500">Page {page} of {Math.ceil(filteredLogs.length/PAGE_SIZE)}</span>
 <button onClick={() => setPage(p => Math.min(Math.ceil(filteredLogs.length/PAGE_SIZE), p+1))} disabled={page === Math.ceil(filteredLogs.length/PAGE_SIZE)}
 className="px-3 py-1 text-xs border border-gray-200 rounded-lg disabled:opacity-40 hover:bg-gray-100">Next →</button>
 </div>
 </div>
 )}
 </div>
 </div>
 </div>
 );
};